---
version: "~> 1.0"

os: linux

language: python

python:
  - '3.8'
  - '3.7'
  - '3.6'

services: docker

cache:
  pip: true
  directories:
  - ".tox"

install:
  - pip install tox-travis git-semver flake8

env:
  jobs:
    - TOX_DISTRO=debian10          TOX_ANSIBLE=latest
    - TOX_DISTRO=debian9           TOX_ANSIBLE=latest
    - TOX_DISTRO=debian8           TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu2004        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1804        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1604        TOX_ANSIBLE=latest
    - TOX_DISTRO=ubuntu1404        TOX_ANSIBLE=latest
    - TOX_DISTRO=centos8           TOX_ANSIBLE=latest
    - TOX_DISTRO=centos7           TOX_ANSIBLE=latest
    - TOX_DISTRO=centos6           TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora32          TOX_ANSIBLE=latest
    - TOX_DISTRO=fedora31          TOX_ANSIBLE=latest
    - TOX_DISTRO=debian10          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian9           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=debian8           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu2004        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1804        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1604        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=ubuntu1404        TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos8           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos7           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=centos6           TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora32          TOX_ANSIBLE={29,28}
    - TOX_DISTRO=fedora31          TOX_ANSIBLE={29,28}

script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION} | tr -d .)-ansible${TOX_ANSIBLE}-${TOX_DISTRO}
  - |
    rm -r .tox/py*/log/*
    find . -type f -name '*.py[co]' -delete -o -type d -name __pycache__ -delete

#deploy:
#  provider: script
#  skip_cleanup: true
#  script: .travis_releaser.sh
#  on:
#    branch: master

branches:
  only:
    - master

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
