---
- name: Set variable if is systemd jobs
  set_fact:
    is_systemd_job: True
  when: item.systemd_jobs is defined

- name: Deploy cron script
  template:
    src: 'restic.cron.j2'
    dest: '/etc/cron.d/restic-{{ item.name }}'
    mode: '0640'
  no_log: true
  when: is_systemd_job is undefined

- name: Deploy helper commands
  template:
    src: 'restic.helper.j2'
    dest: "{{ restic_install_path }}/restic-{{ item.name }}"
    owner: "{{ restic_user }}"
    group: "{{ restic_group }}"
    mode: '0750'
  no_log: true

- name: Get repository name
  set_fact:
    repo_name: "{{ item.name }}"

- include: systemd.yml
  loop: "{{ item.systemd_jobs|flatten(levels=1) }}"
  loop_control:
    loop_var: systemd_job
  when: is_systemd_job is defined
  tags:
    - systemd

- name: Check if repo is already initialized
  command: "{{ restic_install_path }}/restic-{{ item.name }} snapshots"
  changed_when: false
  failed_when: false
  check_mode: false
  no_log: true
  register: repo

- name: Initialize restic repositories
  command: "{{ restic_install_path }}/restic-{{ item.name }} init"
  ignore_errors: true
  no_log: true
  when:
    - repo.rc != 0
    - restic_initialize_repos
